name: First Workflow
on: workflow-dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello from Ubuntu"
      - name: Say Goodbye
        run: echo "Goodbye !!!"