name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: |
          echo "Hello from Ubuntu"
          echo "Additional output"
      - name: Say Goodbye
        run: echo "Goodbye !!!"